name: Install httpd

on: [workflow_dispatch, push]

jobs:
  InstallHttpd:
    runs-on: ubuntu-latest
    steps:
      - run: sudo which yum || sudo yum install yum -y
      - run: sudo yum update -y
      - run: sudo yum install -y httpd
      - run: sudo systemctl start httpd
      - run: sudo systemctl enable httpd
      - run: curl http://localhost:80/
