name: Install httpd

on: [workflow_dispatch, push]

jobs:
  install-httpd:
    runs-on: self-hosted
    steps:
      - run: sudo yum update -y
      - run: sudo yum install -y httpd
      - run: sudo systemctl start httpd
      - run: sudo systemctl enable httpd
      - run: curl http://localhost:80/
